#!/bin/bash

RIG_NUMBER="1"
ETC_ADDRESS="YOUR_ETC_ADDRESS_HERE"
POWERLIMIT_WATTS=106
CORE_OVERCLOCK=-200
MEMORY_OVERCLOCK=900
FAN_SPEED=50
CHATID="YOUR_CHATID"
APIKEY="YOUR_APIKEY"

#########################################################################
telegram()
{
LF=''
sleep 2
GPU_COUNT=$(nvidia-smi --query-gpu=count --format=csv,noheader,nounits | tail -1)
MSG="
$LF $WORKERNAME
$LF RIG_NUMBER__MAC__IP
$LF GPU_COUNT: $GPU_COUNT
https://etc.ethermine.org/miners/$ETC_ADDRESS/dashboard
$LF $FAIL"
/usr/bin/curl -m 5 -s -X POST --output /dev/null https://api.telegram.org/bot${APIKEY}/sendMessage -d "text=${MSG}" -d chat_id=${CHATID}
echo $MSG
sleep 5
}
XORG="FAIL"
if grep -q "28800" /etc/X11/xorg.conf;
then
XORG="OK"
fi
if [ $XORG == "FAIL" ]
then
sudo cp '/etc/X11/xorg.conf.backup' '/etc/X11/xorg.conf'
echo "Xorg PROBLEM DETECTED; Restoring Xorg; Rebooting in 5"
sleep 5
sudo reboot
fi
IPW=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
IP_AS_WORKER=$(echo -n $IPW | tail -c -3 | sed 'y/./0/')
MAC=$(ifconfig -a | grep -Po 'HWaddr \K.*$')
MAC_AS_WORKER=$(echo -n $MAC | tail -c -4 | sed 's|[:,]||g')
sleep 2
sudo nvidia-smi -pl $POWERLIMIT_WATTS
GPUS=$(nvidia-smi --query-gpu=count --format=csv,noheader,nounits | tail -1)
NVD=nvidia-settings
gpu=0
crash=0
while [ $gpu -lt $GPUS ]
do
${NVD} -a [gpu:$gpu]/GPUGraphicsClockOffset[2]=$CORE_OVERCLOCK
${NVD} -a [gpu:$gpu]/GPUMemoryTransferRateOffset[2]=$MEMORY_OVERCLOCK
${NVD} -a [gpu:$gpu]/GPUGraphicsClockOffset[3]=$CORE_OVERCLOCK
${NVD} -a [gpu:$gpu]/GPUMemoryTransferRateOffset[3]=$MEMORY_OVERCLOCK
gpu=$(($gpu+1))
done
gpu=0
MANUAL_FANS=1
while [ $gpu -lt $GPUS ]
do
if [ $FAN_SPEED -lt 50 ]
then
MANUAL_FANS=0
fi
${NVD} -a [gpu:$gpu]/GPUFanControlState=$MANUAL_FANS
${NVD} -a [fan:$gpu]/GPUTargetFanSpeed=$FAN_SPEED
gpu=$(($gpu+1))
done
WORKERNAME=$RIG_NUMBER'__'$MAC_AS_WORKER'__'$IP_AS_WORKER
telegram
CLIENT="/home/m1/eth/10_2/ethdcrminer64 -epool us1-etc.ethermine.org:4444 -ewal $ETC_ADDRESS.$WORKERNAME -epsw x -mode 1 -dbg -1 -wd 0 -mport -3333;"
until $CLIENT
do
FAIL="rebooting"
crash=$(($crash+1))
if [ $crash == 3 ]
then
sudo reboot
fi
telegram
done
fi
